In [3]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv('/content/train (1).csv')

In [5]:
data.shape

(891, 12)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
data.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [9]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [10]:
all = data.Survived.value_counts(True)
print(f"Tiriklar: {all[0]*100} %")
print(f"Omon qolmaganlar: {all[1]*100} %")
print(f"Omonlar soni: {data.Survived.value_counts()[1]}")
print(data.Pclass.value_counts())

Tiriklar: 61.61616161616161 %
Omon qolmaganlar: 38.38383838383838 %
Omonlar soni: 342
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [11]:
print(data.groupby('Sex')["Survived"].mean())
print(data.groupby('Pclass')["Survived"].mean())

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64
Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [12]:
data.groupby(data['Age'] < 12)['Survived'].mean()

Age
False    0.368165
True     0.573529
Name: Survived, dtype: float64

In [13]:
data.groupby(data['SibSp'] | data['Parch'] > 0)['Survived'].mean()

False    0.303538
True     0.505650
Name: Survived, dtype: float64

In [14]:
pd.crosstab(data['Sex'], data['Pclass'], values=data['Survived'], aggfunc='mean')
#

Pclass         1         2         3
Sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [15]:
df = data[['Pclass', 'Fare']]
corr = df.corr()
print(corr)

        Pclass    Fare
Pclass  1.0000 -0.5495
Fare   -0.5495  1.0000

In [16]:
df = data[['Pclass', 'Survived']]
corr = df.corr()
print(corr)

            Pclass  Survived
Pclass    1.000000 -0.338481
Survived -0.338481  1.000000

In [17]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [18]:
data['Fare'].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [19]:
data.isnull().sum()
(data.isnull().sum()/len(df) * 100).round(1)

PassengerId     0.0
Survived        0.0
Pclass          0.0
Name            0.0
Sex             0.0
Age            19.9
SibSp           0.0
Parch           0.0
Ticket          0.0
Fare            0.0
Cabin          77.1
Embarked        0.2
dtype: float64

In [20]:
data = data.drop('Cabin', axis=1)

In [21]:
data['Age'] = data['Age'].fillna(data['Age'].median())

In [22]:
data = data.dropna(subset=['Embarked'])

In [23]:
(data.isnull().sum()/len(df) * 100).round(1)

PassengerId    0.0
Survived       0.0
Pclass         0.0
Name           0.0
Sex            0.0
Age            0.0
SibSp          0.0
Parch          0.0
Ticket         0.0
Fare           0.0
Embarked       0.0
dtype: float64

In [24]:
data.shape

(889, 11)

In [25]:
Q1, Q3 = data["Fare"].quantile([0.25, 0.75])
IQR = Q3 - Q1
out = data[data["Fare"] > Q3 + 1.5 * IQR]

len(out)

114

In [26]:
data['Fare'].max()

512.3292

In [27]:
data['family_size'] = data['SibSp'] + data['Parch'] + 1
data['is_alone'] = data['family_size'] = 1

data['family_size'].describe()

count    889.0
mean       1.0
std        0.0
min        1.0
25%        1.0
50%        1.0
75%        1.0
max        1.0
Name: family_size, dtype: float64

In [28]:
data['is_alone'].value_counts()

is_alone
1    889
Name: count, dtype: int64

In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Sex_encoded'] = le.fit_transform(data['Sex'])
le.classes_


dummies = pd.get_dummies(data['Embarked'], prefix='Embarked')
print(dummies.shape)
data = pd.concat([data, dummies], axis=1)

(889, 3)